### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by for-coursera** [Usbac/nmly#1]
Hi!

`nmly` does compile on macOS 10.11 and shows help but segfaults if run with no parameters (`Segmentation fault: 11`), and when run with parameters, doesn't really do anything (or am I missing something?):

    test> dir
    total 0
    -rw-r--r-- 1 s 0 Sep 27 06:18 1.txt
    -rw-r--r-- 1 s 0 Sep 27 06:18 2.txt
    test> ../nmly after world -d ./
    Apply the changes in the following directory './'? [Y/n]
    test> dir
    total 0
    -rw-r--r-- 1 s 0 Sep 27 06:18 1.txt
    -rw-r--r-- 1 s 0 Sep 27 06:18 2.txt
    test> ../nmly replace txt text -d ./
    Apply the changes in the following directory './'? [Y/n]
    test> dir
    total 0
    -rw-r--r-- 1 s 0 Sep 27 06:18 1.txt
    -rw-r--r-- 1 s 0 Sep 27 06:18 2.txt

Here's its build log:

    gcc -v -c nmly.c
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin15.6.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin
     "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name nmly.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 274.2 -v -dwarf-column-info -debugger-tuning=lldb -coverage-file /Users/me/Desktop/nmly/nmly.c -resource-dir /Library/Developer/CommandLineTools/usr/bin/../lib/clang/8.0.0 -fdebug-compilation-dir /Users/s/Desktop/nmly -ferror-limit 19 -fmessage-length 181 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o nmly.o -x c nmly.c
    clang -cc1 version 8.0.0 (clang-800.0.42.1) default target x86_64-apple-darwin15.6.0
    #include "..." search starts here:
    #include <...> search starts here:
     /usr/local/include
     /Library/Developer/CommandLineTools/usr/bin/../lib/clang/8.0.0/include
     /Library/Developer/CommandLineTools/usr/include
     /usr/include
     /System/Library/Frameworks (framework directory)
     /Library/Frameworks (framework directory)
    End of search list.
    gcc -v -c helper.c
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin15.6.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin
     "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name helper.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 274.2 -v -dwarf-column-info -debugger-tuning=lldb -coverage-file /Users/me/Desktop/nmly/helper.c -resource-dir /Library/Developer/CommandLineTools/usr/bin/../lib/clang/8.0.0 -fdebug-compilation-dir /Users/s/Desktop/nmly -ferror-limit 19 -fmessage-length 181 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o helper.o -x c helper.c
    clang -cc1 version 8.0.0 (clang-800.0.42.1) default target x86_64-apple-darwin15.6.0
    #include "..." search starts here:
    #include <...> search starts here:
     /usr/local/include
     /Library/Developer/CommandLineTools/usr/bin/../lib/clang/8.0.0/include
     /Library/Developer/CommandLineTools/usr/include
     /usr/include
     /System/Library/Frameworks (framework directory)
     /Library/Frameworks (framework directory)
    End of search list.
    gcc -v -o nmly nmly.o helper.o
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin15.6.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin
     "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.11.0 -o nmly nmly.o helper.o -lSystem /Library/Developer/CommandLineTools/usr/bin/../lib/clang/8.0.0/lib/darwin/libclang_rt.osx.a

**Comment by for-coursera** [comment]
Also, a simple Makefile I was using to make life a bit easier (consider including one may be?):

    all: nmly
    
    nmly: nmly.o helper.o
    	 gcc -v -o nmly helper.o nmly.o
    
    helper.o: helper.c
    	 gcc -v -c helper.c
    
    nmly.o: nmly.c
    	 gcc -v -c nmly.c
    
    clean:
    	 rm *.o nmly

(It may wrong or stupid, though: I don't really know anything about C :))

**Comment by Usbac** [comment]
The segmentation fault is now fixed and the makefile has been added. 88d393e

Currently I don't have a macOS environment to test your bug related to Nmly not doing anything, but I will try to get it.

Thank you so much :)

**Comment by for-coursera** [comment]
Thanks for your interest! Also, checked, it doesn't segfaults any more :)

However, it still doesn't seem to do anything -- or may be I'm just using it wrong? Below is some log:

    nmly> mkdir test; cd test
    test> touch daba.txt yaba.txt # I also filled those two files with some LOREM IPSUM just in case :)
    test> ../nmly # to ensure we are indeed testing this latest version, which doesn't segfaults
    USAGE
    
    $ nmly [Arg] [options...]
    
    [rest skipped, it seems OK]
    
    test> ../nmly replace aba zooo -d ./
    Apply the changes in the following directory './'? [Y/n]
    test> dir
    total 8.0K
    -rw-r--r-- 1 s 1.5K Sep 28 19:54 daba.txt
    -rw-r--r-- 1 s 1.5K Sep 28 19:54 yaba.txt
    test> ../nmly replace aba zooo -d ./
    Apply the changes in the following directory './'? [Y/n] n
    test> dir
    total 8.0K
    -rw-r--r-- 1 s 1.5K Sep 28 19:54 daba.txt
    -rw-r--r-- 1 s 1.5K Sep 28 19:54 yaba.txt
    test> ../nmly after world -d ./
    Apply the changes in the following directory './'? [Y/n]
    test> dir
    total 8.0K
    -rw-r--r-- 1 s 1.5K Sep 28 19:54 daba.txt
    -rw-r--r-- 1 s 1.5K Sep 28 19:54 yaba.txt

**Comment by for-coursera** [comment]
I found it!

You need indeed to say `y` to that directory question, just pressing `Enter` is not enough. So, it does work after all :)

(But.. it actually shouldn't even ask, right? Because I provide the path with that ` -d ./` argument, am I correct?)

**Comment by Usbac** [comment]
I'm glad to see that :) 

And Nmly always ask for confirmation even when you specify the directory because you could be doing a potentially dangerous action (like running one of the options in your root directory with the recursive flag, or forgetting to put the preview flag).

**Comment by for-coursera** [comment]
> I'm glad to see that :)

Any plans to make that `Enter` work, though? :)

**Comment by Usbac** [comment]
> > I'm glad to see that :)
> 
> Any plans to make that `Enter` work, though? :)

Yes, it's already done in the current commit 4c30399 :)
